###Problem 1
Create a function load_employees that loads the employees table from the attached file Employees.xls and sets the index of the DataFrame to the EmployeeID. The function should return a table with the EmployeeID as the index and the remaining 25 columns.

In [181]:
import numpy as np
import pandas as pd

In [2]:
def load_employees(sheetname):
    filepath = ("~/Desktop/%s" % (sheetname))
    df = pd.read_excel(filepath)
    df = df.set_index("EmployeeID")
    return df

In [3]:
load_employees("Employee.xlsx")

,Unnamed: 0,NationalIDNumber,LoginID,OrganizationNode,OrganizationLevel,JobTitle,BirthDate,MaritalStatus,Gender,HireDate,...,MiddleName,LastName,BusinessEntityID,AddressID,AddressLine1,AddressLine2,City,StateProvinceID,PostalCode,StateProvinceName
EmployeeID,,,,,,,,,,,,,,,,,,,,,
1,0,295847284,adventure-works\ken0,NaN,0,Chief Executive Officer,1969-01-29,S,M,2009-01-14,...,J,SÃ¡nchez,1,249,4350 Minute Dr.,NaN,Newport Hills,79,98006,Washington
2,1,245797967,adventure-works\terri0,58,1,Vice President of Engineering,1971-08-01,S,F,2008-01-31,...,Lee,Duffy,2,293,7559 Worth Ct.,NaN,Renton,79,98055,Washington
3,2,509647174,adventure-works\roberto0,5AC0,2,Engineering Manager,1974-11-12,M,M,2007-11-11,...,NaN,Tamburello,3,224,2137 Birchwood Dr,NaN,Redmond,79,98052,Washington
4,3,112457891,adventure-works\rob0,5AD6,3,Senior Tool Designer,1974-12-23,S,M,2007-12-05,...,NaN,Walters,4,11387,5678 Lakeview Blvd.,NaN,Minneapolis,36,55402,Minnesota
5,4,695256908,adventure-works\gail0,5ADA,3,Design Engineer,1952-09-27,M,F,2008-01-06,...,A,Erickson,5,190,9435 Breck Court,NaN,Bellevue,79,98004,Washington
6,5,998320692,adventure-works\jossef0,5ADE,3,Design Engineer,1959-03-11,M,M,2008-01-24,...,H,Goldberg,6,286,5670 Bel Air Dr.,NaN,Renton,79,98055,Washington
7,6,134969118,adventure-works\dylan0,5AE1,3,Research and Development Manager,1987-02-24,M,M,2009-02-08,...,A,Miller,7,49,7048 Laurel,NaN,Kenmore,79,98028,Washington
8,7,811994146,adventure-works\diane1,5AE158,4,Research and Development Engineer,1986-06-05,S,F,2008-12-29,...,L,Margheim,8,230,475 Santa Maria,NaN,Everett,79,98201,Washington
9,8,658797903,adventure-works\gigi0,5AE168,4,Research and Development Engineer,1979-01-21,M,F,2009-01-16,...,N,Matthew,9,187,7808 Brown St.,NaN,Bellevue,79,98004,Washington
10,9,879342154,adventure-works\michael6,5AE178,4,Research and Development Manager,1984-11-30,M,M,2009-05-03,...,NaN,Raheem,10,11386,1234 Seaside Way,NaN,San Francisco,9,94109,California
11,10,974026903,adventure-works\ovidiu0,5AE3,3,Senior Tool Designer,1978-01-17,S,M,2010-12-05,...,V,Cracium,11,32505,5458 Gladstone Drive,NaN,Kenmore,79,98028,Washington
12,11,480168528,adventure-works\thierry0,5AE358,4,Tool Designer,1959-07-29,M,M,2007-12-11,...,B,D'Hers,12,1,1970 Napa Ct.,NaN,Bothell,79,98011,Washington
13,12,486228782,adventure-works\janice0,5AE368,4,Tool Designer,1989-05-28,M,F,2010-12-23,...,M,Galvin,13,219,3397 Rancho View Drive,NaN,Redmond,79,98052,Washington
14,13,42487730,adventure-works\michael8,5AE5,3,Senior Design Engineer,1979-06-16,S,M,2010-12-30,...,I,Sullivan,14,295,6510 Hacienda Drive,NaN,Renton,79,98055,Washington
15,14,56920285,adventure-works\sharon0,5AE7,3,Design Engineer,1961-05-02,M,F,2011-01-18,...,B,Salavaria,15,287,7165 Brock Lane,NaN,Renton,79,98055,Washington
16,15,24756624,adventure-works\david0,68,1,Marketing Manager,1975-03-19,S,M,2007-12-20,...,M,Bradley,16,214,3768 Door Way,NaN,Redmond,79,98052,Washington
17,16,253022876,adventure-works\kevin0,6AC0,2,Marketing Assistant,1987-05-03,S,M,2007-01-26,...,F,Brown,17,234,7883 Missing Canyon Court,NaN,Everett,79,98201,Washington
18,17,222969461,adventure-works\john5,6B40,2,Marketing Specialist,1978-03-06,S,M,2011-02-07,...,L,Wood,18,209,9906 Oak Grove Road,NaN,Redmond,79,98052,Washington
19,18,52541318,adventure-works\mary2,6BC0,2,Marketing Assistant,1978-01-29,S,F,2011-02-14,...,A,Dempsey,19,174,6307 Greenbelt Way,NaN,Bellevue,79,98004,Washington
20,19,323403273,adventure-works\wanida0,6C20,2,Marketing Assistant,1975-03-17,M,F,2011-01-07,...,M,Benshoof,20,191,6951 Harmony Way,NaN,Sammamish,79,98074,Washington
21,20,243322160,adventure-works\terry0,6C60,2,Marketing Specialist,1986-02-04,M,M,2009-03-02,...,J,Eminhizer,21,171,8668 Via Neruda,NaN,Bellevue,79,98004,Washington
22,21,95958330,adventure-works\sariya0,6CA0,2,Marketing Specialist,1987-05-21,S,M,2008-12-12,...,E,Harnpadoungsataya,22,233,1185 Dallas Drive,NaN,Everett,79,98201,Washington
23,22,767955365,adventure-works\mary0,6CE0,2,Marketing Specialist,1962-09-13,M,F,2009-01-12,...,E,Gibson,23,229,3928 San Francisco,NaN,Everett,79,98201,Washington
24,23,72636981,adventure-works\jill0,6D10,2,Marketing Specialist,1979-06-18,M,F,2009-01-18,...,A,Williams,24,243,3238 Laguna Circle,NaN,Everett,79,98201,Washington
25,24,519899904,adventure-works\james1,78,1,Vice President of Production,1983-01-07,S,M,2009-02-03,...,R,Hamilton,25,63,9652 Los Angeles,NaN,Monroe,79,98272,Washington
26,25,277173473,adventure-works\peter0,7AC0,2,Production Control Manager,1982-11-03,M,M,2008-12-01,...,J,Krebs,26,166,3670 All Ways Drive,NaN,Bellevue,79,98004,Washington
27,26,446466105,adventure-works\jo0,7AD6,3,Production Supervisor - WC60,1956-10-08,S,F,2008-02-27,...,A,Brown,27,77,9693 Mellowood Street,NaN,Duvall,79,98019,Washington
28,27,14417807,adventure-works\guy1,7AD6B0,4,Production Technician - WC60,1988-03-13,M,M,2006-06-30,...,R,Gilbert,28,61,7726 Driftwood Drive,NaN,Monroe,79,98272,Washington
29,28,948320468,adventure-works\mark1,7AD6D0,4,Production Technician - WC60,1979-09-25,S,M,2009-01-23,...,K,McArthur,29,218,9863 Ridge Place,NaN,Redmond,79,98052,Washington
30,29,410742000,adventure-works\britta0,7AD6F0,4,Production Technician - WC60,1989-09-28,M,F,2009-01-29,...,L,Simon,30,155,2046 Las Palmas,NaN,Edmonds,79,98020,Washington
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,260,280633567,adventure-works\reinout0,85EBAE,4,Purchasing Assistant,1978-01-17,M,M,2010-12-25,...,N,Hillmann,261,173,620 Woodside Ct.,NaN,Bellevue,79,98004,Washington
262,261,231203233,adventure-works\david5,8610,2,Assistant to the Chief Financial Officer,1964-06-21,S,M,2009-01-12,...,M,Barber,262,251,8967 Hamilton Ave.,NaN,Newport Hills,79,98006,Washington
263,262,441044382,adventure-works\jean0,8C,1,Information Services Manager,1975-12-13,S,F,2008-12-11,...,E,Trenary,263,210,2383 Pepper Drive,NaN,Redmond,79,98052,Washington
264,263,858323870,adventure-works\stephanie0,8D60,2,Network Manager,1984-03-25,S,F,2009-02-04,...,A,Conroy,264,268,7435 Ricardo,NaN,Issaquah,79,98027,Washington
265,264,749389530,adventure-works\ashvini0,8D6B,3,Network Administrator,1977-03-27,S,M,2008-12-04,...,R,Sharma,265,270,6580 Poor Ridge Court,NaN,Issaquah,79,98027,Washington
266,265,672243793,adventure-works\peter1,8D6D,3,Network Administrator,1980-05-28,S,M,2009-02-23,...,I,Connelly,266,269,9530 Vine Lane,NaN,Issaquah,79,98027,Washington
267,266,58317344,adventure-works\karen1,8DA0,2,Application Specialist,1978-05-19,S,F,2009-02-16,...,A,Berg,267,274,5256 Chickpea Ct.,NaN,Issaquah,79,98027,Washington
268,267,314747499,adventure-works\ramesh0,8DE0,2,Application Specialist,1988-03-13,S,M,2009-02-03,...,V,Meyyappan,268,273,3848 East 39th Street,NaN,Issaquah,79,98027,Washington
269,268,671089628,adventure-works\dan0,8E10,2,Application Specialist,1987-05-26,M,M,2009-01-11,...,K,Bacon,269,272,1921 Ranch Road,NaN,Issaquah,79,98027,Washington
270,269,643805155,adventure-works\franÃ§ois0,8E30,2,Database Administrator,1975-05-17,S,M,2009-01-17,...,P,Ajenstat,270,267,1144 Paradise Ct.,NaN,Issaquah,79,98027,Washington
271,270,929666391,adventure-works\dan1,8E50,2,Database Administrator,1976-01-06,M,M,2009-01-22,...,B,Wilson,271,32520,5863 Sierra,NaN,Bellevue,79,98004,Washington
272,271,525932996,adventure-works\janaina0,8E70,2,Application Specialist,1985-01-30,M,F,2008-12-23,...,Barreiro Gambaro,Bueno,272,271,5979 El Pueblo,NaN,Issaquah,79,98027,Washington
273,272,112432117,adventure-works\brian3,94,1,Vice President of Sales,1977-06-06,S,M,2011-02-15,...,S,Welcker,273,279,7772 Golden Meadow,NaN,Issaquah,79,98027,Washington
274,273,502097814,adventure-works\stephen0,9560,2,North American Sales Manager,1951-10-17,M,M,2011-01-04,...,Y,Jiang,274,216,2427 Notre Dame Ave.,NaN,Redmond,79,98052,Washington
275,274,841560125,adventure-works\michael9,956B,3,Sales Representative,1968-12-25,S,M,2011-05-31,...,G,Blythe,275,38,8154 Via Mexico,NaN,Detroit,35,48226,Michigan
276,275,191644724,adventure-works\linda3,956D,3,Sales Representative,1980-02-27,M,F,2011-05-31,...,C,Mitchell,276,27,2487 Riverside Drive,NaN,Nevada,74,84407,Utah
277,276,615389812,adventure-works\jillian0,956F,3,Sales Representative,1962-08-29,S,F,2011-05-31,...,NaN,Carson,277,24,80 Sunview Terrace,NaN,Duluth,36,55802,Minnesota
278,277,234474252,adventure-works\garrett1,957080,3,Sales Representative,1975-02-04,M,M,2011-05-31,...,R,Vargas,278,33,10203 Acorn Avenue,NaN,Calgary,1,T2P 2G8,Alberta
279,278,716374314,adventure-works\tsvi0,957180,3,Sales Representative,1974-01-18,M,M,2011-05-31,...,Michael,Reiter,279,29,8291 Crossbow Way,NaN,Memphis,72,38103,Tennessee
280,279,61161660,adventure-works\pamela0,957280,3,Sales Representative,1974-12-06,S,F,2011-05-31,...,O,Ansman-Wolfe,280,22,636 Vine Hill Way,NaN,Portland,58,97205,Oregon
281,280,139397894,adventure-works\shu0,957380,3,Sales Representative,1968-03-09,M,M,2011-05-31,...,K,Ito,281,26,5725 Glaze Drive,NaN,San Francisco,9,94109,California
282,281,399771412,adventure-works\josÃ©1,957440,3,Sales Representative,1963-12-11,M,M,2011-05-31,...,Edvaldo,Saraiva,282,31,9100 Sheppard Avenue North,NaN,Ottawa,57,K4B 1T7,Ontario
283,282,987554265,adventure-works\david8,9574C0,3,Sales Representative,1974-02-11,S,M,2011-05-31,...,R,Campbell,283,32507,2284 Azalea Avenue,NaN,Bellevue,79,98004,Washington
284,283,90836195,adventure-works\tete0,957540,3,Sales Representative,1978-01-05,M,M,2012-09-30,...,A,Mensa-Annan,284,39,3997 Via De Luna,NaN,Cambridge,30,02139,Massachusetts
285,284,481044938,adventure-works\syed0,95A0,2,Pacific Sales Manager,1975-01-11,M,M,2013-03-14,...,E,Abbas,285,3,7484 Roundtree Drive,NaN,Bothell,79,98011,Washington
286,285,758596752,adventure-works\lynn0,95AB,3,Sales Representative,1977-02-14,S,F,2013-05-30,...,N,Tsoflias,286,36,34 Waterloo Road,NaN,Melbourne,77,3000,Victoria
287,286,982310417,adventure-works\amy0,95E0,2,European Sales Manager,1957-09-20,M,F,2012-04-16,...,E,Alberts,287,300,5009 Orange Street,NaN,Renton,79,98055,Washington
288,287,954276278,adventure-works\rachel0,95EB,3,Sales Representative,1975-07-09,S,F,2013-05-30,...,B,Valdez,288,35,Pascalstr 951,NaN,Berlin,20,14111,Hamburg
289,288,668991357,adventure-works\jae0,95ED,3,Sales Representative,1968-03-17,M,F,2012-05-30,...,B,Pak,289,37,Downshire Way,NaN,Cambridge,14,BA5 3HX,England
290,289,134219713,adventure-works\ranjit0,95EF,3,Sales Representative,1975-09-30,S,M,2012-05-30,...,R,Varkey Chudukatil,290,34,"94, rue Descartes",NaN,Bordeaux,119,33000,Gironde

###Problem 2
Define a function getFullName which takes the employees table and a single employee ID as arguments, and returns a string with the full name of the employee in the format "LAST, FIRST MIDDLE".
If the given ID does not belong to any employee return the string "UNKNOWN" (in all caps)
If no middle name is given only return "LAST, FIRST". Make sure there are not trailing spaces.
If only the middle initial is given the return the full name in the format "LAST, FIRST M." with the middle initial followed by a '.'.

Arguments:
- df (DataFrame): Employee Table
- empid (int): Employee ID

Returns:
- String with full name

In [4]:
import pandas as pd
def getFullName(filename,empid):
    filepath = ("~/Desktop/%s" % (filename))
    df = pd.read_excel(filepath)
    df = df.set_index("EmployeeID")
    dfzero = df.fillna(0)
    if empid in dfzero.index:
        first = dfzero.loc[empid, "FirstName"]
        last = dfzero.loc[empid, "LastName"]
        middle = dfzero.loc[empid, "MiddleName"]
        if middle == 0:
            print (last + ", " + first)
        elif len(middle) == 1:
            print (last + ", " + first + " " + middle + ".")
        else:
            print (last + ", " + first + " " + middle)
    else:
        print (empid)
        return ("UNKNOWN")

In [5]:
getFullName("Employee.xlsx",6)

Goldberg, Jossef H.

###Problem 3
Define a function isSales that takes the job title of an employee as string as an argument and return either True if the job title indicates this person works in sales, and False otherwise.

Argument:
- jobtitle (str)

Returns:
- True or False

In [6]:
def isSales(jobtitle):
    if "sale" in jobtitle.lower():
        return True
    else:
        return False

In [11]:
result = isSales("VP")
print (result)
if result == False:
    print ("Y")

False
Y

###Problem 4
Define a function filterSales with the employee tables as an argument, that returns a new table of the same schema (i.e. columns and index) containing only row of sales people. You should use the isSales function from the previous problem.

Arguments:
- employees (DataFrame)

Returns:
- DataFrame with only people form the Sales Department

In [31]:
dataf = pd.read_excel("~/Desktop/Employee.xlsx")
dataf
sales_filter = dataf.loc[:, "JobTitle"].apply(isSales)
sales_filter

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
260    False
261    False
262    False
263    False
264    False
265    False
266    False
267    False
268    False
269    False
270    False
271    False
272     True
273     True
274     True
275     True
276     True
277     True
278     True
279     True
280     True
281     True
282     True
283     True
284     True
285     True
286     True
287     True
288     True
289     True
Name: JobTitle, Length: 290, dtype: bool

In [44]:
def filterSales(datafile):
    filepath = ("~/Desktop/%s" % (datafile))
    df = pd.read_excel(filepath)
    rowcount = df.shape[0]
    for i in range(rowcount):
        title = df.loc[i, "JobTitle"]
        if isSales(title) == False:
            df = df.drop([i])
        else:
            pass
    return df

In [45]:
filterSales("Employee.xlsx")

,Unnamed: 0,EmployeeID,NationalIDNumber,LoginID,OrganizationNode,OrganizationLevel,JobTitle,BirthDate,MaritalStatus,Gender,...,MiddleName,LastName,BusinessEntityID,AddressID,AddressLine1,AddressLine2,City,StateProvinceID,PostalCode,StateProvinceName
272,272,273,112432117,adventure-works\brian3,94,1,Vice President of Sales,1977-06-06,S,M,...,S,Welcker,273,279,7772 Golden Meadow,NaN,Issaquah,79,98027,Washington
273,273,274,502097814,adventure-works\stephen0,9560,2,North American Sales Manager,1951-10-17,M,M,...,Y,Jiang,274,216,2427 Notre Dame Ave.,NaN,Redmond,79,98052,Washington
274,274,275,841560125,adventure-works\michael9,956B,3,Sales Representative,1968-12-25,S,M,...,G,Blythe,275,38,8154 Via Mexico,NaN,Detroit,35,48226,Michigan
275,275,276,191644724,adventure-works\linda3,956D,3,Sales Representative,1980-02-27,M,F,...,C,Mitchell,276,27,2487 Riverside Drive,NaN,Nevada,74,84407,Utah
276,276,277,615389812,adventure-works\jillian0,956F,3,Sales Representative,1962-08-29,S,F,...,NaN,Carson,277,24,80 Sunview Terrace,NaN,Duluth,36,55802,Minnesota
277,277,278,234474252,adventure-works\garrett1,957080,3,Sales Representative,1975-02-04,M,M,...,R,Vargas,278,33,10203 Acorn Avenue,NaN,Calgary,1,T2P 2G8,Alberta
278,278,279,716374314,adventure-works\tsvi0,957180,3,Sales Representative,1974-01-18,M,M,...,Michael,Reiter,279,29,8291 Crossbow Way,NaN,Memphis,72,38103,Tennessee
279,279,280,61161660,adventure-works\pamela0,957280,3,Sales Representative,1974-12-06,S,F,...,O,Ansman-Wolfe,280,22,636 Vine Hill Way,NaN,Portland,58,97205,Oregon
280,280,281,139397894,adventure-works\shu0,957380,3,Sales Representative,1968-03-09,M,M,...,K,Ito,281,26,5725 Glaze Drive,NaN,San Francisco,9,94109,California
281,281,282,399771412,adventure-works\josÃ©1,957440,3,Sales Representative,1963-12-11,M,M,...,Edvaldo,Saraiva,282,31,9100 Sheppard Avenue North,NaN,Ottawa,57,K4B 1T7,Ontario
282,282,283,987554265,adventure-works\david8,9574C0,3,Sales Representative,1974-02-11,S,M,...,R,Campbell,283,32507,2284 Azalea Avenue,NaN,Bellevue,79,98004,Washington
283,283,284,90836195,adventure-works\tete0,957540,3,Sales Representative,1978-01-05,M,M,...,A,Mensa-Annan,284,39,3997 Via De Luna,NaN,Cambridge,30,02139,Massachusetts
284,284,285,481044938,adventure-works\syed0,95A0,2,Pacific Sales Manager,1975-01-11,M,M,...,E,Abbas,285,3,7484 Roundtree Drive,NaN,Bothell,79,98011,Washington
285,285,286,758596752,adventure-works\lynn0,95AB,3,Sales Representative,1977-02-14,S,F,...,N,Tsoflias,286,36,34 Waterloo Road,NaN,Melbourne,77,3000,Victoria
286,286,287,982310417,adventure-works\amy0,95E0,2,European Sales Manager,1957-09-20,M,F,...,E,Alberts,287,300,5009 Orange Street,NaN,Renton,79,98055,Washington
287,287,288,954276278,adventure-works\rachel0,95EB,3,Sales Representative,1975-07-09,S,F,...,B,Valdez,288,35,Pascalstr 951,NaN,Berlin,20,14111,Hamburg
288,288,289,668991357,adventure-works\jae0,95ED,3,Sales Representative,1968-03-17,M,F,...,B,Pak,289,37,Downshire Way,NaN,Cambridge,14,BA5 3HX,England
289,289,290,134219713,adventure-works\ranjit0,95EF,3,Sales Representative,1975-09-30,S,M,...,R,Varkey Chudukatil,290,34,"94, rue Descartes",NaN,Bordeaux,119,33000,Gironde

###Problem 5
Define a function getEmailList with that returns a Series of strings of all email addresses of employees in this state or province. The email addresses should be separated by a given character, usually a comma ',' or semicolon ';'.

Arguments:
- employees (DataFrame)
- delimiter (str)

Returns:
- Series of email addresses, concatenated by the given delimiter. The Series is indexed by the state or province.

In [205]:
def getEmailList(dataname, delimiter):
    filepath = ("~/Desktop/%s" % (dataname))
    dff = pd.read_excel(filepath)
    
    states = dff["StateProvinceName"]
    output = dict()
    for state in states:
        statefilter = dff["StateProvinceName"] == state
        newcol =  ["EmailAddress", "StateProvinceName"]
        emaildf = dff.loc[statefilter, newcol]
        emaillist = list(emaildf["EmailAddress"])
        emailoutput = delimiter.join(emaillist)
        output[state] = emailoutput
    return pd.Series(output).to_frame("Email")

In [206]:
getEmailList("Employee.xlsx", ", ")

                                                           Email
Washington     ken0@adventure-works.com, terri0@adventure-wor...
Minnesota      rob0@adventure-works.com, jillian0@adventure-w...
California     michael6@adventure-works.com, shu0@adventure-w...
Michigan                            michael9@adventure-works.com
Utah                                  linda3@adventure-works.com
Alberta                             garrett1@adventure-works.com
Tennessee                              tsvi0@adventure-works.com
Oregon                               pamela0@adventure-works.com
Ontario                                josÃ©1@adventure-works.com
Massachusetts                          tete0@adventure-works.com
Victoria                               lynn0@adventure-works.com
Hamburg                              rachel0@adventure-works.com
England                                 jae0@adventure-works.com
Gironde                              ranjit0@adventure-works.com