###Question 1
Write a function called "variable_helper" which takes one argument:

df, which is a pandas data frame
and returns:

d, a dictionary where keys are the column names of df and values are one of "numeric", "categorical", "ordinal", "date/time", or "text", corresponding to the feature type of each column.

In [2]:
import pandas as pd
import numpy as np
import json
from pprint import pprint

In [3]:
df = pd.read_csv("~/Desktop/DataProg/COBRA-YTD2017.csv.gz")

In [4]:
df

,MI_PRINX,offense_id,rpt_date,occur_date,occur_time,poss_date,poss_time,beat,apt_office_prefix,apt_office_num,...,dispo_code,MaxOfnum_victims,Shift,Avg Day,loc_type,UC2 Literal,neighborhood,npu,x,y
0,7693210,172490115,09/06/2017,09/06/2017,00:30:00,09/06/2017,00:35:00,607,NaN,NaN,...,NaN,1.0,Morn,Wed,NaN,AGG ASSAULT,Custer/McDonough/Guice,W,-84.35850,33.70839
1,7693211,172490265,09/06/2017,09/05/2017,11:15:00,09/06/2017,02:30:00,512,NaN,NaN,...,NaN,1.0,Eve,Tue,99.0,LARCENY-FROM VEHICLE,Downtown,M,-84.39736,33.74958
2,7693212,172490322,09/06/2017,09/06/2017,03:15:00,09/06/2017,03:45:00,501,NaN,NaN,...,NaN,1.0,Morn,Wed,18.0,LARCENY-FROM VEHICLE,Atlantic Station,E,-84.39776,33.79072
3,7693213,172490390,09/06/2017,09/05/2017,17:45:00,09/06/2017,04:57:00,207,NaN,NaN,...,NaN,1.0,Morn,Tue,18.0,LARCENY-FROM VEHICLE,Brookwood Hills,E,-84.39361,33.80774
4,7693214,172490401,09/06/2017,09/05/2017,17:00:00,09/06/2017,05:00:00,203,NaN,NaN,...,NaN,1.0,Morn,Tue,18.0,LARCENY-FROM VEHICLE,Hills Park,D,-84.43337,33.79848
5,7693215,172490464,09/06/2017,09/06/2017,05:30:00,09/06/2017,05:47:00,605,NaN,NaN,...,NaN,1.0,Morn,Wed,23.0,AUTO THEFT,Grant Park,W,-84.37969,33.74677
6,7693216,172490503,09/06/2017,09/06/2017,06:50:00,09/06/2017,07:10:00,511,NaN,NaN,...,NaN,1.0,Day,Wed,7.0,LARCENY-NON VEHICLE,Downtown,M,-84.38964,33.75194
7,7693217,172490513,09/06/2017,09/06/2017,06:50:00,09/06/2017,07:00:00,508,NaN,NaN,...,NaN,1.0,Morn,Wed,14.0,LARCENY-NON VEHICLE,Downtown,M,-84.38810,33.75809
8,7693218,172490518,09/06/2017,09/06/2017,04:00:00,09/06/2017,07:00:00,408,NaN,NaN,...,NaN,1.0,Morn,Wed,20.0,AUTO THEFT,Venetian Hills,S,-84.44718,33.71866
9,7693219,172490541,09/06/2017,09/06/2017,04:00:00,09/06/2017,05:00:00,401,NaN,NaN,...,NaN,1.0,Morn,Wed,13.0,ROBBERY-PEDESTRIAN,Oakland City,S,-84.42324,33.72798
10,7693220,172490549,09/06/2017,09/03/2017,11:00:00,09/03/2017,12:00:00,505,NaN,NaN,...,NaN,2.0,Day,Sun,6.0,BURGLARY-NONRES,Midtown,E,-84.38932,33.77911
11,7693221,172490557,09/06/2017,09/05/2017,21:00:00,09/06/2017,07:20:00,207,NaN,323,...,NaN,1.0,Morn,Wed,18.0,LARCENY-FROM VEHICLE,Loring Heights,E,-84.40671,33.79742
12,7693222,172490741,09/06/2017,09/06/2017,07:30:00,09/06/2017,08:20:00,506,NaN,NaN,...,NaN,1.0,Day,Wed,20.0,LARCENY-FROM VEHICLE,Midtown,E,-84.37102,33.77686
13,7693223,172490781,09/06/2017,09/05/2017,22:00:00,09/06/2017,05:00:00,212,NaN,NaN,...,NaN,1.0,Morn,Wed,13.0,LARCENY-FROM VEHICLE,Piedmont Heights,F,-84.37157,33.80697
14,7693224,172490796,09/06/2017,09/06/2017,08:30:00,09/06/2017,09:10:00,208,NaN,NaN,...,NaN,1.0,Day,Wed,14.0,AGG ASSAULT,Buckhead Forest,B,-84.37963,33.85134
15,7693225,172490829,09/06/2017,09/06/2017,09:20:00,09/06/2017,09:30:00,401,NaN,NaN,...,NaN,1.0,Day,Wed,18.0,ROBBERY-PEDESTRIAN,West End,T,-84.41593,33.73760
16,7693226,172490896,09/06/2017,09/06/2017,07:00:00,09/06/2017,10:00:00,203,NaN,302,...,NaN,1.0,Day,Wed,20.0,BURGLARY-RESIDENCE,Bolton,D,-84.44920,33.81667
17,7693227,172490914,09/06/2017,09/05/2017,19:30:00,09/06/2017,10:10:00,408,NaN,NaN,...,NaN,1.0,Morn,Wed,20.0,LARCENY-FROM VEHICLE,Venetian Hills,S,-84.44116,33.72205
18,7693228,172490925,09/06/2017,09/06/2017,10:19:00,09/06/2017,10:19:00,414,NaN,NaN,...,NaN,1.0,Day,Wed,12.0,LARCENY-NON VEHICLE,Princeton Lakes,P,-84.51090,33.65573
19,7693229,172490954,09/06/2017,09/06/2017,10:15:00,09/06/2017,10:31:00,414,NaN,330,...,NaN,1.0,Day,Wed,NaN,ROBBERY-COMMERCIAL,Princeton Lakes,P,-84.51020,33.65528
20,7693230,172491015,09/06/2017,09/06/2017,07:00:00,09/06/2017,10:45:00,208,NaN,NaN,...,NaN,1.0,Day,Wed,18.0,LARCENY-FROM VEHICLE,Peachtree Park,B,-84.36815,33.84642
21,7693231,172491018,09/06/2017,09/06/2017,10:30:00,09/06/2017,11:00:00,413,NaN,NaN,...,NaN,1.0,Day,Wed,20.0,LARCENY-FROM VEHICLE,Ben Hill Pines,P,-84.50755,33.68212
22,7693232,172491074,09/06/2017,09/06/2017,11:00:00,09/06/2017,11:36:00,410,NaN,NaN,...,NaN,1.0,Day,Wed,26.0,AUTO THEFT,Campbellton Road,R,-84.45432,33.70264
23,7693233,172491075,09/06/2017,09/06/2017,11:25:00,09/06/2017,11:40:00,411,NaN,NaN,...,NaN,1.0,Day,Wed,20.0,LARCENY-NON VEHICLE,Greenbriar,R,-84.48742,33.68841
24,7693234,172491173,09/06/2017,08/28/2017,21:07:00,08/28/2017,22:03:00,209,NaN,NaN,...,NaN,1.0,Eve,Mon,21.0,LARCENY-NON VEHICLE,East Chastain Park,B,-84.38270,33.85821
25,7693235,172491176,09/06/2017,08/31/2017,00:00:00,09/06/2017,12:54:00,312,NaN,NaN,...,NaN,1.0,Unk,Unk,20.0,BURGLARY-RESIDENCE,Orchard Knob,Z,-84.37872,33.66754
26,7693236,172491268,09/06/2017,09/06/2017,13:00:00,09/06/2017,13:20:00,412,NaN,211,...,NaN,1.0,Day,Wed,26.0,BURGLARY-RESIDENCE,Ben Hill Terrace,P,-84.51830,33.69598
27,7693237,172491272,09/06/2017,09/06/2017,13:15:00,09/06/2017,13:24:00,211,NaN,NaN,...,NaN,1.0,Day,Wed,NaN,LARCENY-NON VEHICLE,Lindbergh/Morosgo,B,-84.36521,33.82400
28,7693238,172491275,09/06/2017,09/06/2017,00:44:00,09/06/2017,15:28:00,210,NaN,NaN,...,NaN,1.0,Day,Wed,8.0,LARCENY-NON VEHICLE,Lenox,B,-84.36212,33.84676
29,7693239,172491281,09/06/2017,09/06/2017,08:00:00,09/06/2017,08:30:00,211,NaN,NaN,...,NaN,1.0,Day,Wed,8.0,LARCENY-NON VEHICLE,Lindbergh/Morosgo,B,-84.36328,33.82403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17395,7675959,170011863,01/01/2017,12/31/2016,10:30:00,01/01/2017,12:00:00,112,NaN,NaN,...,NaN,1.0,Unk,Sat,NaN,LARCENY-FROM VEHICLE,Collier Heights,I,-84.49110,33.78133
17396,7675960,170011877,01/01/2017,01/01/2017,10:35:00,01/01/2017,11:14:00,103,NaN,3000,...,NaN,1.0,Day,Sun,4.0,LARCENY-NON VEHICLE,English Avenue,L,-84.41659,33.76968
17397,7675961,170011922,01/01/2017,12/05/2016,00:00:00,01/01/2017,14:56:00,407,NaN,NaN,...,NaN,1.0,Unk,Unk,NaN,RAPE,Adamsville,H,-84.50586,33.75894
17398,7675962,170011995,01/01/2017,01/01/2017,19:25:00,01/01/2017,19:25:00,303,NaN,NaN,...,NaN,1.0,Eve,Sun,99.0,AUTO THEFT,Mechanicsville,V,-84.40248,33.73642
17399,7675963,170012028,01/01/2017,01/01/2017,14:30:00,01/01/2017,19:30:00,102,NaN,NaN,...,NaN,1.0,Eve,Sun,18.0,LARCENY-FROM VEHICLE,Vine City,L,-84.40771,33.75916
17400,7675964,170012066,01/01/2017,01/01/2017,18:50:00,01/01/2017,20:03:00,311,NaN,NaN,...,NaN,1.0,Eve,Sun,5.0,BURGLARY-NONRES,Hammond Park,X,-84.41268,33.68097
17401,7675965,170012135,01/01/2017,01/01/2017,20:15:00,01/01/2017,20:25:00,113,APT,C301,...,NaN,1.0,Eve,Sun,26.0,BURGLARY-RESIDENCE,Carey Park,G,-84.47156,33.78999
17402,7675966,170012145,01/01/2017,01/01/2017,20:30:00,01/01/2017,20:45:00,209,NaN,NaN,...,NaN,4.0,Eve,Sun,18.0,LARCENY-FROM VEHICLE,North Buckhead,B,-84.38135,33.85547
17403,7675967,170012182,01/01/2017,01/01/2017,21:05:00,01/01/2017,21:07:00,203,NaN,NaN,...,NaN,1.0,Eve,Sun,23.0,LARCENY-FROM VEHICLE,Blandtown,D,-84.42561,33.80058
17404,7675968,170012193,01/01/2017,01/01/2017,21:15:00,01/01/2017,21:20:00,408,NaN,D,...,NaN,1.0,Eve,Sun,99.0,AUTO THEFT,NaN,R,-84.44453,33.71100
17405,7675969,170012234,01/01/2017,12/30/2016,23:00:00,12/30/2016,23:15:00,402,NaN,NaN,...,NaN,1.0,Morn,Fri,12.0,LARCENY-NON VEHICLE,West End,T,-84.43276,33.73812
17406,7675970,170012253,01/01/2017,01/01/2017,21:00:00,01/01/2017,22:00:00,212,NaN,NaN,...,NaN,1.0,Eve,Sun,18.0,LARCENY-FROM VEHICLE,Piedmont Heights,F,-84.36831,33.80965
17407,7675971,170012261,01/01/2017,01/01/2017,22:00:00,01/01/2017,22:21:00,414,NaN,NaN,...,NaN,2.0,Eve,Sun,18.0,LARCENY-FROM VEHICLE,Princeton Lakes,P,-84.50908,33.65571
17408,7675972,170012306,01/01/2017,01/01/2017,20:15:00,01/01/2017,22:54:00,306,NaN,NaN,...,NaN,2.0,Eve,Sun,20.0,BURGLARY-RESIDENCE,Sylvan Hills,X,-84.42393,33.71374
17409,7675973,170012317,01/01/2017,01/01/2017,23:02:00,01/01/2017,23:04:00,612,NaN,NaN,...,NaN,1.0,Morn,Sun,23.0,ROBBERY-PEDESTRIAN,East Atlanta,W,-84.32324,33.72602
17410,7675974,170012332,01/01/2017,01/01/2017,23:14:00,01/01/2017,23:14:00,101,NaN,NaN,...,NaN,1.0,Morn,Sun,13.0,AUTO THEFT,Atlanta University Center,T,-84.40445,33.75389
17411,7675975,170012374,01/01/2017,01/01/2017,23:32:00,01/01/2017,23:42:00,307,NaN,NaN,...,NaN,1.0,Morn,Sun,20.0,AGG ASSAULT,Joyland,Y,-84.39648,33.71008
17412,7675942,170011336,01/01/2017,01/01/2017,13:30:00,01/01/2017,13:40:00,409,NaN,C2,...,NaN,1.0,Day,Sun,5.0,BURGLARY-NONRES,Southwest,R,-84.48046,33.70046
17413,7675943,170011344,01/01/2017,12/31/2016,22:30:00,01/01/2017,13:30:00,406,NaN,NaN,...,NaN,1.0,Morn,Sun,13.0,AUTO THEFT,Magnum Manor,I,-84.49334,33.72723
17414,7675944,170011358,01/01/2017,12/31/2016,19:00:00,01/01/2017,11:00:00,505,NaN,1105,...,NaN,1.0,Unk,Sun,18.0,LARCENY-FROM VEHICLE,Midtown,E,-84.38424,33.77800
17415,7675945,170011435,01/01/2017,12/31/2016,19:05:00,12/31/2016,22:30:00,504,NaN,NaN,...,NaN,1.0,Eve,Sat,13.0,LARCENY-FROM VEHICLE,Marietta Street Artery,E,-84.40612,33.77425
17416,7675946,170011504,01/01/2017,01/01/2017,15:00:00,01/01/2017,15:30:00,602,NaN,NaN,...,NaN,1.0,Eve,Sun,20.0,LARCENY-FROM VEHICLE,Inman Park,N,-84.35289,33.76341
17417,7675947,170011513,01/01/2017,01/01/2017,14:50:00,01/01/2017,15:00:00,208,NaN,NaN,...,10,1.0,Day,Sun,24.0,LARCENY-NON VEHICLE,North Buckhead,B,-84.36235,33.85166
17418,7675948,170011525,01/01/2017,01/01/2017,15:37:00,01/01/2017,15:37:00,303,NaN,NaN,...,NaN,1.0,Eve,Sun,3.0,LARCENY-FROM VEHICLE,Mechanicsville,V,-84.39486,33.73760
17419,7675949,170011531,01/01/2017,01/01/2017,14:15:00,01/01/2017,15:45:00,610,NaN,NaN,...,NaN,1.0,Eve,Sun,21.0,LARCENY-FROM VEHICLE,Kirkwood,O,-84.31645,33.76408
17420,7675950,170011548,01/01/2017,12/03/2016,08:00:00,01/01/2017,15:00:00,211,NaN,NaN,...,NaN,1.0,Unk,Unk,20.0,LARCENY-NON VEHICLE,Peachtree Park,B,-84.36772,33.84482
17421,7675951,170011621,01/01/2017,01/01/2017,17:00:00,01/01/2017,18:00:00,114,NaN,B13,...,10,2.0,Eve,Sun,26.0,LARCENY-NON VEHICLE,Old Gordon,H,-84.51322,33.76797
17422,7675952,170011645,01/01/2017,12/31/2016,20:00:00,01/01/2017,14:00:00,302,NaN,NaN,...,NaN,1.0,Unk,Sun,13.0,LARCENY-FROM VEHICLE,Pittsburgh,V,-84.40465,33.73026
17423,7675953,170011678,01/01/2017,01/01/2017,16:10:00,01/01/2017,16:30:00,205,NaN,NaN,...,NaN,1.0,Eve,Sun,7.0,LARCENY-NON VEHICLE,Wildwood (NPU-C),C,-84.41347,33.81022
17424,7675954,170011682,01/01/2017,12/30/2016,22:00:00,01/01/2017,05:00:00,113,APT,A414,...,NaN,1.0,Unk,Unk,26.0,BURGLARY-RESIDENCE,Carey Park,G,-84.47292,33.78810

In [5]:
print (df.dtypes)

MI_PRINX               int64
offense_id             int64
rpt_date              object
occur_date            object
occur_time            object
poss_date             object
poss_time             object
beat                   int64
apt_office_prefix     object
apt_office_num        object
location              object
MinOfucr               int64
MinOfibr_code         object
dispo_code            object
MaxOfnum_victims     float64
Shift                 object
Avg Day               object
loc_type             float64
UC2 Literal           object
neighborhood          object
npu                   object
x                    float64
y                    float64
dtype: object

In [ ]:
# Assumption 1: 
# If the column name has date or time in it, the data type should be date/time

In [ ]:
# General Thought
# categorical can be either string or numerical
# categorical data does not have to be continous if it is in numerical format
# EX: north, west, east, south
# EX: morning, afternoon, evening, night

In [ ]:
# Assumption 2: 
# if ordinal is in numerical format, it has to meet 2 qualifications:
# continous, meaning that the numbers are in order, either increasing or decreasing
# unique, means the number of unqiue values in a column = the number of rows

In [ ]:
# Assumption 3:
# number of nan in a column > 80% of rows
# then it is bad data

In [ ]:
# Assumption 4:
# after we get rid of data/time and ordinal type
# number of unique is more than > 40% of filled rows
# then it is not categorical
# then it should be numeric or text

In [ ]:
# Assumption 5:
# if the rati is < 10%
# then we do not have a lot of unique values
# then it should be categorical

In [ ]:
# Assuption 6:
# if the ratio is between 10% to 40%
# it is very hard to make the call to label the data as categorical or text or numeric
# I then label them as the default pandas dtype
# however, this case will not occur in this dataframe
# for other dataframes, we can study the data further to get a better understanding

In [6]:
def variable_helper(df):
    col_list = list(df.columns)
    type_list = []
    rownum = len(df.index)
    for col in col_list:
        if df[col].dtypes == "float64":
            # check number of nan values
            # if #nan > 80% , means bad data
            # type should be "text"
            if df[col].isna().sum() > 0.8*rownum:
                type_list.append("text")
                # if #unique = #rows, mean each value is unique
                # type should be ordinal
            else:
                if len(df[col].unique()) == rownum:
                    type_list.append("ordinal")
                else:
                    # unique/(row - nan) > 40% means randomness, type numeric
                    # unique/(row - nan) < 1% means repetitiveness, type categorical
                    ratio = len(df[col].unique())/(rownum - df[col].isna().sum())
                    if ratio > 0.4:
                        type_list.append("numeric")
                    elif ratio < 0.1:
                        type_list.append("categorical")
                    else:
                        type_list.append("float64")
        elif df[col].dtypes == "int64":
            # nan and bad data
            if df[col].isna().sum() > 0.8*rownum:
                type_list.append("text")
            else:
                # check unique
                if len(df[col].unique()) == len(df.index):
                    type_list.append("ordinal")
                else:
                    ratio1 = len(df[col].unique())/(rownum - df[col].isna().sum())
                    if ratio1 > 0.4:
                        # very random
                        type_list.append("numeric")
                    elif ratio1 < 0.1:
                        # not very random
                        type_list.append("categorical")
                    else:
                        type_list.append("int64")
        elif df[col].dtypes == "object":
            # check nan
            if df[col].isna().sum() > 0.8*rownum:
                type_list.append("text")
            else:
                # check unique
                if len(df[col].unique()) == len(df.index):
                    type_list.append("ordinal")
                else:
                    if "date" in col or "time" in col:
                        type_list.append("date/time")
                    else:
                        ratio2 = len(df[col].unique())/(rownum - df[col].isna().sum())
                        if ratio2 > 0.4:
                            # very random
                            # when the dtype is object, this corresponds to text
                            type_list.append("text")
                        elif ratio2 < 0.1:
                            # not very random
                            # type categorical
                            type_list.append("categorical")
                        else:
                            type_list.append("object")
    dict1 = dict(zip(col_list, type_list))
    return dict1
    # use json.dumps to print the dictionary in a nicer way
    print (json.dumps(dict1, indent = 4))

In [7]:
variable_helper(df)

{'MI_PRINX': 'ordinal',
 'offense_id': 'ordinal',
 'rpt_date': 'date/time',
 'occur_date': 'date/time',
 'occur_time': 'date/time',
 'poss_date': 'date/time',
 'poss_time': 'date/time',
 'beat': 'categorical',
 'apt_office_prefix': 'text',
 'apt_office_num': 'text',
 'location': 'text',
 'MinOfucr': 'categorical',
 'MinOfibr_code': 'categorical',
 'dispo_code': 'text',
 'MaxOfnum_victims': 'categorical',
 'Shift': 'categorical',
 'Avg Day': 'categorical',
 'loc_type': 'categorical',
 'UC2 Literal': 'categorical',
 'neighborhood': 'categorical',
 'npu': 'categorical',
 'x': 'numeric',
 'y': 'numeric'}

Question 2
Write a function called "get_categories" which takes one argument:

df, which is a pandas data frame
and returns:

cat, a dictionary where keys are names of columns of df corresponding to categorical features, and values are arrays of all the unique values that the feature can take.

In [293]:
df = pd.read_csv("~/Desktop/DataProg/COBRA-YTD2017.csv.gz")

In [294]:
type(variable_helper(df))

dict

In [295]:
check_dict = variable_helper(df)

In [320]:
np.sort(df["beat"].unique())

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
       313, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
       413, 414, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511,
       512, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612,
       701, 702, 703, 704, 705, 706, 707, 708, 710])

In [372]:
emp = df["UC2 Literal"].unique()
print (emp)
print (type(emp))
emp = emp.astype(str)
np.sort(emp)

['AGG ASSAULT' 'LARCENY-FROM VEHICLE' 'AUTO THEFT' 'LARCENY-NON VEHICLE'
 'ROBBERY-PEDESTRIAN' 'BURGLARY-NONRES' 'BURGLARY-RESIDENCE'
 'ROBBERY-COMMERCIAL' 'RAPE' 'ROBBERY-RESIDENCE' 'HOMICIDE']
<class 'numpy.ndarray'>

array(['AGG ASSAULT', 'AUTO THEFT', 'BURGLARY-NONRES',
       'BURGLARY-RESIDENCE', 'HOMICIDE', 'LARCENY-FROM VEHICLE',
       'LARCENY-NON VEHICLE', 'RAPE', 'ROBBERY-COMMERCIAL',
       'ROBBERY-PEDESTRIAN', 'ROBBERY-RESIDENCE'], dtype='<U20')

In [11]:
def get_categories(df):
    # I need to use the previous function for this question
    check_dict = variable_helper(df)
    col_list = list(df.columns)
    cate_list = []
    value_list = []
    for col in col_list:
        if check_dict[col] == "categorical":
            cate_list.append(col)
            # in order to sort the numpy array
            # need to change nan float to nan string
            value_list.append(np.sort(df[col].unique().astype(str)))
    dict2 = dict(zip(cate_list, value_list))
    return dict2
    # print out the dictionary in a nicer way
    print("\n".join("{}\t{}".format(k, v) for k, v in dict2.items()))

In [12]:
# since I use astype to get rid of float nan value
# the dtype in dictionary does not reflect the real type

In [13]:
get_categories(df)

{'beat': array(['101', '102', '103', '104', '105', '106', '107', '108', '109',
        '110', '111', '112', '113', '114', '201', '202', '203', '204',
        '205', '206', '207', '208', '209', '210', '211', '212', '213',
        '301', '302', '303', '304', '305', '306', '307', '308', '309',
        '310', '311', '312', '313', '401', '402', '403', '404', '405',
        '406', '407', '408', '409', '410', '411', '412', '413', '414',
        '501', '502', '503', '504', '505', '506', '507', '508', '509',
        '510', '511', '512', '601', '602', '603', '604', '605', '606',
        '607', '608', '609', '610', '611', '612', '701', '702', '703',
        '704', '705', '706', '707', '708', '710'], dtype='<U21'),
 'MinOfucr': array(['110', '210', '220', '311', '312', '313', '314', '315', '316',
        '317', '321', '322', '323', '324', '325', '327', '331', '332',
        '333', '334', '335', '336', '337', '341', '342', '343', '344',
        '345', '347', '410', '420', '430', '440', '511', '512', '521',
        '522', '531', '532', '610', '620', '630', '640', '650', '660',
        '670', '680', '690', '710', '720', '730'], dtype='<U21'),
 'MinOfibr_code': array(['0911', '0912', '1006', '1101', '1101A', '1102', '1102A', '1103',
        '1103A', '1201', '1201C', '1201D', '1202', '1202J', '1202K',
        '1202L', '1202Q', '1202R', '1203', '1203X', '1203Y', '1204',
        '1205', '1205K', '1206', '1207', '1208', '1208K', '1209', '1211G',
        '1211O', '1212', '1299G', '1299K', '1299O', '1299S', '1313',
        '1314', '1315', '1315K', '1399', '2202', '2202A', '2203', '2203A',
        '2204', '2205', '2301', '2302', '2303', '2304', '2305', '2307',
        '2308', '2310', '2314', '2316', '2317', '2374', '2399', '2404',
        '2404A', '2424', '2424A', '2434', '2434A', 'nan'], dtype='<U5'),
 'MaxOfnum_victims': array(['0.0', '1.0', '10.0', '11.0', '13.0', '14.0', '17.0', '19.0',
        '2.0', '27.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0',
        'nan'], dtype='<U32'),
 'Shift': array(['Day', 'Eve', 'Morn', 'Unk'], dtype='<U4'),
 'Avg Day': array(['Fri', 'Mon', 'Sat', 'Sun', 'Thu', 'Tue', 'Unk', 'Wed'],
       dtype='<U3'),
 'loc_type': array(['1.0', '10.0', '11.0', '12.0', '13.0', '14.0', '15.0', '17.0',
        '18.0', '19.0', '2.0', '20.0', '21.0', '23.0', '24.0', '26.0',
        '28.0', '29.0', '3.0', '30.0', '31.0', '32.0', '33.0', '34.0',
        '35.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '99.0', 'nan'],
       dtype='<U32'),
 'UC2 Literal': array(['AGG ASSAULT', 'AUTO THEFT', 'BURGLARY-NONRES',
        'BURGLARY-RESIDENCE', 'HOMICIDE', 'LARCENY-FROM VEHICLE',
        'LARCENY-NON VEHICLE', 'RAPE', 'ROBBERY-COMMERCIAL',
        'ROBBERY-PEDESTRIAN', 'ROBBERY-RESIDENCE'], dtype='<U20'),
 'neighborhood': array(['Adair Park', 'Adams Park', 'Adamsville', 'Almond Park',
        'Amal Heights', 'Ansley Park', 'Arden/Habersham', 'Ardmore',
        'Argonne Forest', 'Arlington Estates', 'Ashley Courts',
        'Ashview Heights', 'Atkins Park', 'Atlanta Industrial Park',
        'Atlanta University Center', 'Atlantic Station', 'Audobon Forest',
        'Audobon Forest West', 'Baker Hills', 'Bakers Ferry', 'Bankhead',
        'Bankhead/Bolton', 'Beecher Hills', 'Ben Hill', 'Ben Hill Acres',
        'Ben Hill Forest', 'Ben Hill Pines', 'Ben Hill Terrace',
        'Benteen Park', 'Berkeley Park', 'Betmar LaVilla',
        'Blair Villa/Poole Creek', 'Blandtown', 'Bolton', 'Bolton Hills',
        'Boulder Park', 'Boulevard Heights', 'Brandon', 'Brentwood',
        'Briar Glen', 'Brookhaven', 'Brookview Heights', 'Brookwood',
        'Brookwood Hills', 'Browns Mill Park', 'Buckhead Forest',
        'Buckhead Heights', 'Buckhead Village', 'Bush Mountain',
        'Butner/Tell', 'Cabbagetown', 'Campbellton Road', 'Candler Park',
        'Capitol Gateway', 'Capitol View', 'Capitol View Manor',
        'Carey Park', 'Carroll Heights', 'Carver Hills',
        'Cascade Avenue/Road', 'Cascade Green', 'Cascade Heights',
        'Castleberry Hill', 'Castlewood', 'Center Hill', 'Chalet Woods',
        'Channing Valley', 'Chastain Park', 'Chattahoochee',
        'Chosewood Park', 'Collier Heights', 'Collier Hills',
        'Collier Hills North', 'Colonial Homes', 'Cross Creek',
        'Custer/McDonough/Guice', 'Deerwood', 'Dixie Hills', 'Downtown',
        'Druid Hills', 'East Ardley Road', 'East Atlanta',
        'East Chastain Park', 'East Lake', 'Edgewood', 'Elmco Estates',
        'English Avenue', 'English Park', 'Fairburn', 'Fairburn Heights',
        'Fairburn Mays', 'Fairburn Road/Wisteria Lane', 'Fairburn Tell',
        'Fairway Acres', 'Fernleaf', 'Florida Heights', 'Fort McPherson',
        'Fort Valley', 'Garden Hills', 'Glenrose Heights', 'Grant Park',
        'Green Acres Valley', 'Green Forest Acres', 'Greenbriar',
        'Greenbriar Village', 'Grove Park', 'Hammond Park', 'Hanover West',
        'Harland Terrace', 'Harris Chiles', 'Harvel Homes Community',
        'Heritage Valley', 'High Point', 'Hills Park', 'Home Park',
        'Horseshoe Community', 'Hunter Hills', 'Huntington', 'Inman Park',
        'Ivan Hill', 'Joyland', 'Just Us', 'Kings Forest', 'Kingswood',
        'Kirkwood', 'Knight Park/Howell Station', 'Lake Claire',
        'Lakewood', 'Lakewood Heights', 'Laurens Valley', 'Leila Valley',
        'Lenox', 'Lincoln Homes', 'Lindbergh/Morosgo',
        'Lindridge/Martin Manor', 'Loring Heights', 'Magnum Manor',
        'Margaret Mitchell', 'Marietta Street Artery', 'Mays',
        'Meadowbrook Forest', 'Mechanicsville', 'Mellwood',
        'Memorial Park', 'Midtown', 'Midwest Cascade', 'Monroe Heights',
        'Morningside/Lenox Park', 'Mozley Park', 'Mt. Gilead Woods',
        'Mt. Paran/Northside', 'Niskey Cove', 'Niskey Lake',
        'North Buckhead', 'Norwood Manor', 'Oakcliff', 'Oakland',
        'Oakland City', 'Old Fourth Ward', 'Old Gordon', 'Orchard Knob',
        'Ormewood Park', 'Paces', 'Peachtree Battle Alliance',
        'Peachtree Heights East', 'Peachtree Heights West',
        'Peachtree Hills', 'Peachtree Park', 'Penelope Neighbors',
        'Peoplestown', 'Perkerson', 'Peyton Forest', 'Piedmont Heights',
        'Pine Hills', 'Pittsburgh', 'Pleasant Hill', 'Polar Rock',
        'Pomona Park', 'Poncey-Highland', 'Princeton Lakes',
        'Randall Mill', 'Rebel Valley Forest', 'Reynoldstown',
        'Ridgecrest Forest', 'Ridgedale Park', 'Ridgewood Heights',
        'Riverside', 'Rockdale', 'Rosedale Heights', 'Rue Royal',
        'Sandlewood Estates', 'Scotts Crossing', 'Sherwood Forest',
        'South Atlanta', 'South River Gardens', 'South Tuxedo Park',
        'Southwest', 'Springlake', 'Summerhill', 'Swallow Circle/Baywood',
        'Sweet Auburn', 'Sylvan Hills', 'Tampa Park',
        'The Villages at Carver', 'The Villages at Castleberry H',
        'The Villages at East Lake', 'Thomasville Heights', 'Tuxedo Park',
        'Underwood Hills', 'Venetian Hills', 'Vine City',
        'Virginia Highland', 'Washington Park', 'Wesley Battle',
        'West End', 'West Highlands', 'West Lake', 'West Manor',
        'West Paces Ferry/Northside', 'Westhaven', 'Westminster/Milmar',
        'Westover Plantation', 'Westview', 'Westwood Terrace',
        'Whitewater Creek', 'Whittier Mill Village', 'Wildwood (NPU-C)',
        'Wildwood (NPU-H)', 'Wildwood Forest', 'Wilson Mill Meadows',
        'Wisteria Gardens', 'Woodfield', 'Woodland Hills', 'Wyngate',
        'nan'], dtype='<U29'),
 'npu': array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
        'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z', 'nan'],
       dtype='<U3')}

Question 3
Write a function called "code_shift" which takes one argument:

df, which is a pandas data frame
and returns:

a pandas data frame with columns "offense_id", "Shift", "ShiftID", where ShiftID is 0 if "Shift" is "Unk", 1 if "Morn", 2 if "Day", and 3 if "Eve".

In [410]:
df = pd.read_csv("~/Desktop/DataProg/COBRA-YTD2017.csv.gz")

In [14]:
df1 = df[['offense_id','Shift']]
def code_shift(df1):
    ShiftID = df["Shift"].map({'Unk': '0', 'Morn': '1', 'Day':'2', 'Eve':'3'})
    df1["ShiftID"] = ShiftID
    return df1

In [15]:
code_shift(df1)

/Users/xiaofeixue/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

       offense_id Shift ShiftID
0       172490115  Morn       1
1       172490265   Eve       3
2       172490322  Morn       1
3       172490390  Morn       1
4       172490401  Morn       1
5       172490464  Morn       1
6       172490503   Day       2
7       172490513  Morn       1
8       172490518  Morn       1
9       172490541  Morn       1
10      172490549   Day       2
11      172490557  Morn       1
12      172490741   Day       2
13      172490781  Morn       1
14      172490796   Day       2
15      172490829   Day       2
16      172490896   Day       2
17      172490914  Morn       1
18      172490925   Day       2
19      172490954   Day       2
20      172491015   Day       2
21      172491018   Day       2
22      172491074   Day       2
23      172491075   Day       2
24      172491173   Eve       3
25      172491176   Unk       0
26      172491268   Day       2
27      172491272   Day       2
28      172491275   Day       2
29      172491281   Day       2
...           ...   ...     ...
17395   170011863   Unk       0
17396   170011877   Day       2
17397   170011922   Unk       0
17398   170011995   Eve       3
17399   170012028   Eve       3
17400   170012066   Eve       3
17401   170012135   Eve       3
17402   170012145   Eve       3
17403   170012182   Eve       3
17404   170012193   Eve       3
17405   170012234  Morn       1
17406   170012253   Eve       3
17407   170012261   Eve       3
17408   170012306   Eve       3
17409   170012317  Morn       1
17410   170012332  Morn       1
17411   170012374  Morn       1
17412   170011336   Day       2
17413   170011344  Morn       1
17414   170011358   Unk       0
17415   170011435   Eve       3
17416   170011504   Eve       3
17417   170011513   Day       2
17418   170011525   Eve       3
17419   170011531   Eve       3
17420   170011548   Unk       0
17421   170011621   Eve       3
17422   170011645   Unk       0
17423   170011678   Eve       3
17424   170011682   Unk       0

[17425 rows x 3 columns]

Question 4
Write a function called "rating_confusion" which takes one argument:

cer, which is a pandas data frame
and returns:

cf, a confusion matrix where the rows correspond to predicted_ratingID and the columns correspond to ratingID.

In [16]:
cer = pd.read_csv("~/Desktop/DataProg/cereal.csv")

In [17]:
cer

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,ratingID,predicted_ratingID
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.00,0.33,68.402973,1,1
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.00,1.00,33.983679,0,0
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.00,0.33,59.425505,0,0
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.00,0.50,93.704912,1,1
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.00,0.75,34.384843,0,1
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.00,0.75,29.509541,0,0
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.00,1.00,33.174094,0,0
7,Basic 4,G,C,130,3,2,210,2.0,18.0,8,100,25,3,1.33,0.75,37.038562,0,0
8,Bran Chex,R,C,90,2,1,200,4.0,15.0,6,125,25,1,1.00,0.67,49.120253,0,1
9,Bran Flakes,P,C,90,3,0,210,5.0,13.0,5,190,25,3,1.00,0.67,53.313813,0,1
10,Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,12,35,25,2,1.00,0.75,18.042851,0,0
11,Cheerios,G,C,110,6,2,290,2.0,17.0,1,105,25,1,1.00,1.25,50.764999,0,0
12,Cinnamon Toast Crunch,G,C,120,1,3,210,0.0,13.0,9,45,25,2,1.00,0.75,19.823573,0,0
13,Clusters,G,C,110,3,2,140,2.0,13.0,7,105,25,3,1.00,0.50,40.400208,0,0
14,Cocoa Puffs,G,C,110,1,1,180,0.0,12.0,13,55,25,2,1.00,1.00,22.736446,0,0
15,Corn Chex,R,C,110,2,0,280,0.0,22.0,3,25,25,1,1.00,1.00,41.445019,0,0
16,Corn Flakes,K,C,100,2,0,290,1.0,21.0,2,35,25,1,1.00,1.00,45.863324,0,0
17,Corn Pops,K,C,110,1,0,90,1.0,13.0,12,20,25,2,1.00,1.00,35.782791,0,0
18,Count Chocula,G,C,110,1,1,180,0.0,12.0,13,65,25,2,1.00,1.00,22.396513,0,0
19,Cracklin' Oat Bran,K,C,110,3,3,140,4.0,10.0,7,160,25,3,1.00,0.50,40.448772,0,0
20,Cream of Wheat (Quick),N,H,100,3,0,80,1.0,21.0,0,-1,0,2,1.00,1.00,64.533816,1,0
21,Crispix,K,C,110,2,0,220,1.0,21.0,3,30,25,3,1.00,1.00,46.895644,0,0
22,Crispy Wheat & Raisins,G,C,100,2,1,140,2.0,11.0,10,120,25,3,1.00,0.75,36.176196,0,1
23,Double Chex,R,C,100,2,0,190,1.0,18.0,5,80,25,3,1.00,0.75,44.330856,0,0
24,Froot Loops,K,C,110,2,1,125,1.0,11.0,13,30,25,2,1.00,1.00,32.207582,0,0
25,Frosted Flakes,K,C,110,1,0,200,1.0,14.0,11,25,25,1,1.00,0.75,31.435973,0,0
26,Frosted Mini-Wheats,K,C,100,3,0,0,3.0,14.0,7,100,25,2,1.00,0.80,58.345141,0,1
27,"Fruit & Fibre Dates, Walnuts, and Oats",P,C,120,3,2,160,5.0,12.0,10,200,25,3,1.25,0.67,40.917047,0,0
28,Fruitful Bran,K,C,120,3,0,240,5.0,14.0,12,190,25,3,1.33,0.67,41.015492,0,0
29,Fruity Pebbles,P,C,110,1,1,135,0.0,13.0,12,25,25,2,1.00,0.75,28.025765,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,Multi-Grain Cheerios,G,C,100,2,1,220,2.0,15.0,6,90,25,1,1.00,1.00,40.105965,0,0
48,Nut&Honey Crunch,K,C,120,2,1,190,0.0,15.0,9,40,25,2,1.00,0.67,29.924285,0,0
49,Nutri-Grain Almond-Raisin,K,C,140,3,2,220,3.0,21.0,7,130,25,3,1.33,0.67,40.692320,0,1
50,Nutri-grain Wheat,K,C,90,3,0,170,3.0,18.0,2,90,25,3,1.00,1.00,59.642837,0,1
51,Oatmeal Raisin Crisp,G,C,130,3,2,170,1.5,13.5,10,120,25,3,1.25,0.50,30.450843,0,0
52,Post Nat. Raisin Bran,P,C,120,3,1,200,6.0,11.0,14,260,25,3,1.33,0.67,37.840594,0,0
53,Product 19,K,C,100,3,0,320,1.0,20.0,3,45,100,3,1.00,1.00,41.503540,0,1
54,Puffed Rice,Q,C,50,1,0,0,0.0,13.0,0,15,0,3,0.50,1.00,60.756112,1,1
55,Puffed Wheat,Q,C,50,2,0,0,1.0,10.0,0,50,0,3,0.50,1.00,63.005645,1,0
56,Quaker Oat Squares,Q,C,100,4,1,135,2.0,14.0,6,110,25,3,1.00,0.50,49.511874,0,0
57,Quaker Oatmeal,Q,H,100,5,2,0,2.7,-1.0,-1,110,0,1,1.00,0.67,50.828392,0,0
58,Raisin Bran,K,C,120,3,1,210,5.0,14.0,12,240,25,2,1.33,0.75,39.259197,0,0
59,Raisin Nut Bran,G,C,100,3,2,140,2.5,10.5,8,140,25,3,1.00,0.50,39.703400,0,0
60,Raisin Squares,K,C,90,2,0,0,2.0,15.0,6,110,25,3,1.00,0.50,55.333142,0,1
61,Rice Chex,R,C,110,1,0,240,0.0,23.0,2,30,25,1,1.00,1.13,41.998933,0,0
62,Rice Krispies,K,C,110,2,0,290,0.0,22.0,3,35,25,1,1.00,1.00,40.560159,0,0
63,Shredded Wheat,N,C,80,2,0,0,3.0,16.0,0,95,0,1,0.83,1.00,68.235885,1,1
64,Shredded Wheat 'n'Bran,N,C,90,3,0,0,4.0,19.0,0,140,0,1,1.00,0.67,74.472949,1,1
65,Shredded Wheat spoon size,N,C,90,3,0,0,3.0,20.0,0,120,0,1,1.00,0.67,72.801787,1,0
66,Smacks,K,C,110,2,1,70,1.0,9.0,15,40,25,2,1.00,0.75,31.230054,0,0
67,Special K,K,C,110,6,0,230,1.0,16.0,3,55,25,1,1.00,1.00,53.131324,0,0
68,Strawberry Fruit Wheats,N,C,90,2,0,15,3.0,15.0,5,90,25,2,1.00,1.00,59.363993,0,0
69,Total Corn Flakes,G,C,110,2,1,200,0.0,21.0,3,35,100,3,1.00,1.00,38.839746,0,0
70,Total Raisin Bran,G,C,140,3,1,190,4.0,15.0,14,230,100,3,1.50,1.00,28.592785,0,0
71,Total Whole Grain,G,C,100,3,1,200,3.0,16.0,3,110,100,3,1.00,1.00,46.658844,0,1
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.00,0.75,39.106174,0,0
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.00,1.00,27.753301,0,0
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.00,0.67,49.787445,0,1
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.00,1.00,51.592193,0,0
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.00,0.75,36.187559,0,0

In [30]:
df_ml = cer[:20]
def rating_confusion (df_ml):
    # prediction value
    y_pred = df_ml["predicted_ratingID"]
    # real value
    y_real = df_ml["ratingID"]
    # create the matrix
    df_conf = pd.crosstab(y_pred, y_real, rownames=['PredictedRatingID'], colnames=['RatingID'])
    return df_conf

In [31]:
rating_confusion(df_ml)

RatingID            0  1
PredictedRatingID
0                  15  0
1                   3  2

In [83]:
rating_confusion(cer)

RatingID            0  1
PredictedRatingID
0                  58  3
1                  11  5

Question 5
Write a function called "prediction_metrics" which takes one argument:

cer, which is a pandas data frame
and returns:

metrics_dict, a python dictionary object where the keys are 'precision', 'recall', 'F1' and the values are the numeric values for precision, recall, and F1 score, where ratingID is the prediction target and predicted_ratingID is a model output.

###Accuracy = (TP + TN) / (TP + TN + FP + FN)
###Recall=TP / (TP + FN)
###Precision = TP / (TP + FP)
###Fmeasure=(2*Recall*Precision)/(Recall+Presision)

In [77]:
metrics = cer[["ratingID", "predicted_ratingID"]]
def prediction_metrics (metrics):
    TP = 0
    TN = 0
    FP = 0
    FN = 0
    # create variables to store values
    for i in range(len(metrics.index)):
        if metrics["ratingID"][i] == 1 and metrics["predicted_ratingID"][i] == 1:
            # we have true positive
            TP = TP + 1
        elif metrics["ratingID"][i] == 1 and metrics["predicted_ratingID"][i] == 0:
            # we have false negative
            FN = FN + 1
        elif metrics["ratingID"][i] == 0 and metrics["predicted_ratingID"][i] == 0:
            # we have true negative
            TN = TN + 1
        elif metrics["ratingID"][i] == 0 and metrics["predicted_ratingID"][i] == 1:
            # we have false positive
            FP = FP + 1
        else:
            print ("Wrong Data")
    precision = TP/(TP + FP)
    recall = TP / (TP + FN)
    F1 = 2*precision*recall / (recall + precision)
    metrics_dict = {"F1": F1, "precision": precision, "recall": recall}
    return metrics_dict

In [78]:
prediction_metrics(metrics)

{'F1': 0.4166666666666667, 'precision': 0.3125, 'recall': 0.625}

In [82]:
prediction_metrics(cer[:20])

{'F1': 0.5714285714285715, 'precision': 0.4, 'recall': 1.0}